#### Tableau Explanations:

Description of "Anomaly by Disaster Type"
Occurrence for each Disaster Type broken down by Occurrence.  Color shows details about Predicate.
Marks

The mark type is Bar.
Stacked marks is on.

Shelves

Rows:
Measure Names, Occurrence
Columns:
Disaster Type
Color:
Predicate

Dimensions
Measure Names has 1 members on this sheet
Members: Occurrence
Disaster Type has 11 members on this sheet
Members: Drought; Earthquake (seismic activity); Mass movement dry; Mass movement wet; Wildfire; ...
Disaster Type is sorted descending by Occurrence.
Measures
Predicate has 2 members on this sheet
Members: 0; 1




Description of "Sig. Ratio vs. Damage GDP Ratio"

Average of Significance Ratio vs. average of Damage GDP Ratio. Color shows details about INCOME_GROUP. Details are shown for Country Name and Disaster Type. The data is filtered on sum of Significance Ratio, average of LOG10 Total Damage, sum of Damage GDP Ratio and sum of Total Damage. The sum of Significance Ratio filter keeps non-Null values only. The average of LOG10 Total Damage filter keeps non-Null values only. The sum of Damage GDP Ratio filter keeps non-Null values only. The sum of Total Damage filter ranges from 1 to 210,000,000. The view is filtered on INCOME_GROUP and Exclusions (Country Name,INCOME_GROUP,Year 2). The INCOME_GROUP filter keeps High income: OECD, High income: nonOECD, Low income, Lower middle income and Upper middle income. The Exclusions (Country Name,INCOME_GROUP,Year 2) filter keeps 4,027 members.

Marks
The mark type is Shape (Automatic).
Stacked marks is off. 

Shelves
 Pages:
 Year

 Rows:
 Avg. Damage GDP Ratio
 
 Columns
 Avg. Significance Ratio
 
 Filters:
  Significance Ratio, Avg. LOG10 Total Damage, INCOME_GROUP, Exclusions (Country Name,INCOME_GROUP,Year 2), Damage GDP Ratio, Total Damage
 

 Level of detail:
 Country Name, Disaster Type
 
 Color:
 INCOME_GROUP
 

Dimensions

Country Name has 156 members on this sheet

Members: Albania; Argentina; Bangladesh; Belgium; The Bahamas; ...

Disaster Type has 11 members on this sheet

Members: Drought; Earthquake (seismic activity); Flood; Mass Movement Wet; Storm; …

INCOME_GROUP has 5 members on this sheet

Members: High income: OECD; High income: nonOECD; Low income; Lower middle income; Upper middle income

Year has 53 members on this sheet

Members: 1963; 1966; 1976; 1995; 2002; ...

Measures

Average of Significance Ratio ranges from 0.0000 to 0.9629 on this sheet.

The formula is ([Homeless]+[Deaths]+[Affected]+[Injured])/[Population]

Average of LOG10 Total Damage has the value Null on this sheet.

The filter associated with this field keeps non-Null values only.

The formula is LOG([Total Damage],10)

Average of Damage GDP Ratio ranges from 0.0000 to 0.2484 on this sheet.

The formula is ([Total Damage]*100)/[Gdp Us Dollars]

Sum of Significance Ratio has the value Null on this sheet.

The filter associated with this field keeps non-Null values only.

The formula is ([Homeless]+[Deaths]+[Affected]+[Injured])/[Population]

Sum of Damage GDP Ratio has the value Null on this sheet.

The filter associated with this field keeps non-Null values only.

The formula is ([Total Damage]*100)/[Gdp Us Dollars]

Sum of Total Damage ranges from 1 to 210,000,000 on this sheet.

The filter associated with this field ranges from 1 to 210,000,000.

Sets

Exclusions (Country Name,INCOME_GROUP,Year 2) has 1,754 members on this sheet

Members: Albania, Upper middle income, 2002; Bangladesh, Low income, 1963; Bangladesh, Low income, 1966; Bangladesh, Low income, 1976; Belgium, High income: OECD, 2002; ...


Description of "Sig. Ratio by Income Group "

The plot of average of Significance Ratio for Year. Color shows details about INCOME GROUP. Details are shown for Country Name and Disaster Type. The view is filtered on average of Significance Ratio and INCOME GROUP. The average of Significance Ratio filter keeps non-Null values only. The INCOME GROUP filter keeps High income: OECD, High income: nonOECD, Low income, Lower middle income and Upper middle income.

Marks


The mark type is Bar.
 

Stacked marks is on.
 

Shelves


Rows:
 
Avg. Significance Ratio
 

Columns:
 
Year
 

Filters:
 
Avg. Significance Ratio, INCOME_GROUP
 

Level of detail:
 
Country Name, Disaster Type
 

Color:
 
INCOME_GROUP
 

Dimensions

Country Name has 181 members on this sheet

Members: Afghanistan; Albania; Angola; Belgium; Burundi; ...

Disaster Type has 11 members on this sheet

Members: Drought; Earthquake (seismic activity); Flood; Mass Movement Wet; Storm; ...

INCOME_GROUP has 5 members on this sheet

Members: High income: OECD; High income: nonOECD; Low income; Lower middle income; Upper middle income

Year ranges from 1961.00 to 2013.00 on this sheet.

Measures

Average of Significance Ratio ranges from 0.000 to 1.564 on this sheet.

The filter associated with this field keeps non-Null values only.

The formula is ([Homeless]+[Deaths]+[Affected]+[Injured])/[Population]



Description of "Damage GDP Ratio by Income Group"

The plot of average of Damage GDP Ratio for Year. Color shows details about INCOME_GROUP. Details are shown for Country Name and Disaster Type. The data is filtered on sum of Damage GDP Ratio, which ranges from 0.002 to 1.

Marks


The mark type is Bar.
 

Stacked marks is on.
 

Shelves


Rows:
 
Avg. Damage GDP Ratio
 

Columns:
 
Year
 

Filters:
 
Damage GDP Ratio
 

Level of detail:
 
Country Name, Disaster Type
 

Color:
 
INCOME_GROUP
 

Dimensions

Country Name has 84 members on this sheet

Members: Armenia; Bangladesh; Bermuda; Comoros; The Bahamas; ...

Disaster Type has 9 members on this sheet

Members: Drought; Earthquake (seismic activity); Flood; Storm; Wildfire; ...

INCOME_GROUP has 5 members on this sheet

Members: High income: OECD; High income: nonOECD; Low income; Lower middle income; Upper middle income

Year ranges from 1961.00 to 2013.00 on this sheet.

Measures

Average of Damage GDP Ratio ranges from 0.0020 to 0.2484 on this sheet.

The formula is ([Total Damage]*100)/[Gdp Us Dollars]

Sum of Damage GDP Ratio ranges from 0.002 to 1 on this sheet.

The filter associated with this field ranges from 0.002 to 1.

The formula is ([Total Damage]*100)/[Gdp Us Dollars]




Description of "Low Income Group Disasters"

Average of Damage GDP Ratio and average of Significance Ratio. Color shows details about Disaster Type. Details are shown for INCOME_GROUP. The view is filtered on INCOME_GROUP and average of Damage GDP Ratio. The INCOME_GROUP filter keeps Low income and Lower middle income. The average of Damage GDP Ratio filter keeps non-Null values only.

Average of Damage GDP Ratio Properties

Marks

The mark type is Bar (Automatic).
 

Stacked marks is on.
 

Shelves


Rows:
 
Avg. Damage GDP Ratio, Avg. Significance Ratio
 

Filters:
 
INCOME_GROUP, Avg. Damage GDP Ratio
 

Level of detail:
 
INCOME_GROUP
 

Color:
 
Disaster Type
 

Average of Significance Ratio Properties

Marks


The mark type is Bar (Automatic).
 

Stacked marks is on.
 

Shelves


Rows:
 
Avg. Damage GDP Ratio, Avg. Significance Ratio
 

Filters:
 
INCOME_GROUP, Avg. Damage GDP Ratio
 

Level of detail:
 
INCOME_GROUP
 

Color:
 
Disaster Type
 

Dimensions

Disaster Type has 11 members on this sheet

Members: Drought; Epidemic; Extreme temperature; Insect Infestation; Mass Movement Dry; ...

INCOME_GROUP has 2 members on this sheet

Members: Low income; Lower middle income

Measures

Average of Significance Ratio ranges from 0.0000 to 0.1265 on this sheet.

The formula is ([Homeless]+[Deaths]+[Affected]+[Injured])/[Population]

Average of Damage GDP Ratio ranges from 0.000000 to 0.005298 on this sheet.

The filter associated with this field keeps non-Null values only.

The formula is ([Total Damage]*100)/[Gdp Us Dollars]



Description of "High Income Group Disasters"

Average of Damage GDP Ratio and average of Significance Ratio. Color shows details about Disaster Type. Details are shown for INCOME_GROUP. The view is filtered on INCOME_GROUP, which keeps High income: OECD.

Average of Significance Ratio Properties

Marks



The mark type is Bar (Automatic).
 

Stacked marks is on.
 

Shelves



Rows:
 
Avg. Damage GDP Ratio, Avg. Significance Ratio
 

Filters:
 
INCOME_GROUP
 

Level of detail:
 
INCOME_GROUP
 

Color:
 
Disaster Type
 

Average of Damage GDP Ratio Properties



Shelves

Rows:
 
Avg. Damage GDP Ratio, Avg. Significance Ratio
 

Filters:
 
INCOME_GROUP
 

Level of detail:
 
INCOME_GROUP
 

Color:
 
Disaster Type
 

Dimensions

Disaster Type has 11 members on this sheet

Members: Drought; Earthquake (seismic activity); Extreme temperature; Flood; Wildfire; ...

INCOME_GROUP has 1 members on this sheet

Members: High income: OECD

Measures

Average of Significance Ratio ranges from 0.00000 to 0.01450 on this sheet.

The formula is ([Homeless]+[Deaths]+[Affected]+[Injured])/[Population]

Average of Damage GDP Ratio ranges from 0.0000000 to 0.0006007 on this sheet.

The formula is ([Total Damage]*100)/[Gdp Us Dollars]


Description of "Upper Middle High nonOECD Income Group Disasters"

Average of Damage GDP Ratio and average of Significance Ratio. Color shows details about Disaster Type. Details are shown for INCOME_GROUP. The view is filtered on INCOME_GROUP, which keeps High income: nonOECD and Upper middle income.

Average of Significance Ratio Properties

Marks


The mark type is Bar (Automatic).
 

Stacked marks is on.
 

Shelves

Rows:
 
Avg. Damage GDP Ratio, Avg. Significance Ratio
 

Filters:
 
INCOME_GROUP
 

Level of detail:
 
INCOME_GROUP
 

Color:
 
Disaster Type
 

Average of Damage GDP Ratio Properties

Marks






The mark type is Bar (Automatic).
 

Stacked marks is on.
 

Shelves







Rows:
 
Avg. Damage GDP Ratio, Avg. Significance Ratio
 

Filters:
 
INCOME_GROUP
 

Level of detail:
 
INCOME_GROUP
 

Color:
 
Disaster Type
 

Dimensions

Disaster Type has 11 members on this sheet

Members: Earthquake (seismic activity); Epidemic; Flood; Storm; Volcano; ...

INCOME_GROUP has 2 members on this sheet

Members: High income: nonOECD; Upper middle income

Measures

Average of Significance Ratio ranges from 0.00000 to 0.05288 on this sheet.

The formula is ([Homeless]+[Deaths]+[Affected]+[Injured])/[Population]

Average of Damage GDP Ratio ranges from 0.000000 to 0.002699 on this sheet.

The formula is ([Total Damage]*100)/[Gdp Us Dollars]



Description of "Disaster Trends"

The plot of count of Disaster Type for Year broken down by Disaster Type. Color shows details about INCOME_GROUP.

Marks


The mark type is Bar.
 

Stacked marks is on.
 

Shelves



Rows:
 
Disaster Type, Count of Disaster Type
 

Columns:
 
Year
 

Color:
 
INCOME_GROUP
 

Dimensions

Disaster Type has 11 members on this sheet

Members: Earthquake (seismic activity); Epidemic; Extreme temperature; Flood; Mass Movement Wet; ...

INCOME_GROUP has 6 members on this sheet

Members: High income: OECD; High income: nonOECD; Low income; Lower middle income; Upper middle income; ...

Year ranges from 1961.00 to 2014.00 on this sheet.

Measures

Count of Disaster Type ranges from 1 to 29 on this sheet.




Data Source Details
Data Source:
EMDAT_WORLDBANK (DS_NATURAL_DISASTERS)
 

Type:
Oracle Database
 

Server:
128.83.138.158
 

Server Version:
12.1.0.1.0 - Oracle Database 12c Enterprise Edition (64bit Production)
 

Table: 
EMDAT_WORLDBANK

Username:
ds_natural_disasters

#### Top 10 Locations of Tsunami deaths since 2010


load("../02NaturalDisastersData/frames/tsunami_deaths_top10.RData")
t<- gvisGeoMap(data=tsunami_deaths_top10, locationvar="LATLONG",
               numvar="DEATHS", hovervar="DATA",
               options=list(colors="[0xECE7F2,0xA6BDDB,0x2B8CBE]",width="750px",height="500px", dataMode="markers"))
plot(t)
print(t, tag = "chart")

####Top 10 Financial loss due to Tsunamis since 2010

load("../02NaturalDisastersData/frames/tsunami_financial_top10.RData")
t<- gvisGeoMap(data=tsunami_financial_top10, locationvar="LATLONG",
               numvar="MILLIONS OF DOLLARS", hovervar="DATA",
               options=list(colors="[0xECE7F2,0xA6BDDB,0x2B8CBE]",width="750px",height="500px", dataMode="markers"))
plot(t)
print(t, tag = "chart")


#### Top 10 Locations of Volcano related deaths since 1944

load("../02NaturalDisastersData/frames/volcano_deaths_top10.RData")
t<- gvisGeoMap(data=volcano_deaths_top10, locationvar="LATLONG",
               numvar="DEATHS", hovervar="DATA",
               options=list(colors="[0xECE7F2,0xA6BDDB,0x2B8CBE]",width="750px",height="500px", dataMode="markers"))
plot(t)
print(t, tag = "chart")


####Top 8 Financial damages due to Volcanoes since 1944

load("../02NaturalDisastersData/frames/volcano_financial_top10.RData")
t<- gvisGeoMap(data=volcano_financial_top10, locationvar="LATLONG",
               numvar="MILLIONS OF DOLLARS", hovervar="DATA",
               options=list(colors="[0xECE7F2,0xA6BDDB,0x2B8CBE]",width="750px",height="500px", dataMode="markers"))
plot(t)
print(t, tag = "chart")
